-- 새로 생성할 manager 테이블
CREATE TABLE IF NOT EXISTS manager (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_day TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_day TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- 새로 생성할 schedule 테이블
CREATE TABLE IF NOT EXISTS schedule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    manager_id BIGINT NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_day TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_day TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (manager_id) REFERENCES manager(id)
);
